SecondHand/Models/Negotiation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SecondHand.Models
{
    public class Negotiation
    {
        public int id { get; set; }
        public string seller { get; set; }
        public string buyer { get; set; }
        public int productId { get; set; }
        public int control { get; set; }
    }
}

SecondHand/Controllers/NegotiationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SecondHand.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace SecondHand.Controllers
{
    public class NegotiationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Negotiations
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var test = (from a in db.Negotiations where (a.buyer == userId || a.seller == userId) select a).ToList();

            return View(test);
        }

        // GET: Negotiations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Negotiation negotiation = db.Negotiations.Find(id);
            if (negotiation == null)
            {
                return HttpNotFound();
            }
            return View(negotiation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TerminateNegotiation(int id)
        {
            Negotiation negotiation = db.Negotiations.Find(id);
            Product product = db.Products.Find(negotiation.productId);
            product.state = 0;
            product.negotiation = null;
            db.Negotiations.Remove(negotiation);
            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NegotiationSuccessful(int id)
        {
            Negotiation negotiation = db.Negotiations.Find(id);
            Product product = db.Products.Find(negotiation.productId);
            if (negotiation.control == 0)
            {
                negotiation.control++;
                //product.negotiation.control++;
                db.Entry(product).State = EntityState.Modified;
                db.Entry(negotiation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            if(negotiation.control == 1)
            {
                negotiation.control++;
                //product.negotiation.control++;
                product.state = 2;
                var AdminData = db.AdminDatas.FirstOrDefault();
                AdminData.SoldProducts++;
                db.Entry(AdminData).State = EntityState.Modified;
                db.Entry(product).State = EntityState.Modified;
                db.Entry(negotiation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Rating", new { id = negotiation.seller });
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Negotiations/Rating
        public ActionResult Rating(string id)
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(id);
            var MyList = new List<int> { 0, 1, 2, 3, 4 , 5};
            SelectList items2 = new SelectList(MyList);

            ViewBag.MyList = items2;

            return View(user);
        }

        //POST: Negotiations/Rating/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RatingPost(string id, int rating)
        {

            ApplicationUser user = db.Users.Find(id);

            if (rating == 0) user.Rating -= 3;
            if (rating == 1) user.Rating -= 2;
            if (rating == 3) user.Rating += 2;
            if (rating == 4) user.Rating += 4;
            if (rating == 5) user.Rating += 5;
            user.NumberOfRatings++;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        // GET: Negotiations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Negotiation negotiation = db.Negotiations.Find(id);
            if (negotiation == null)
            {
                return HttpNotFound();
            }
            return View(negotiation);
        }

        // POST: Negotiations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Negotiation negotiation = db.Negotiations.Find(id);
            Product product = db.Products.Find(negotiation.productId);
            product.negotiation = null;
            product.state = 0;
            db.Entry(product).State = EntityState.Modified;
            db.Negotiations.Remove(negotiation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SecondHand/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SecondHand.Models;
using SecondHand.ViewModels;
using System.Web.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.Web.UI.WebControls;

namespace SecondHand.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index()
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user;
            var products = db.Products.Include(p => p.Category);
            foreach(Product p in products)
            {
                user = userManager.FindByIdAsync(p.owner).Result;
                p.owner = user.FullName;
            }
            return View(products.ToList());
        }

        public ActionResult MyProducts()
        {
            var userId = User.Identity.GetUserId();
            var products = (from p in db.Products where p.owner == userId select p).OrderBy(x => x.state);
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user;
            foreach (Product p in products)
            {
                user = userManager.FindByIdAsync(p.owner).Result;
                p.owner = user.FullName;
            }
            return View("Index", products.ToList());
        }

        // GET: Products/Search
        public ActionResult Search(string Query)
        {

            var products = (from p in db.Products select p);
            if (!String.IsNullOrEmpty(Query))
            {
                products = products.Where(s => s.Name.Contains(Query)).OrderBy(x => x.state);
            }
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user;
            foreach (Product p in products)
            {
                user = userManager.FindByIdAsync(p.owner).Result;
                p.owner = user.FullName;
            }
            return View(products.ToList());
        }

        public ActionResult DeleteComment(int productId, int pos, string userId)
        {
            if (userId == User.Identity.GetUserId())
            {
                Product product = db.Products.Find(productId);
                product.Questions.Remove(product.Questions.ElementAt(pos));
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = productId });
            }
            else return HttpNotFound();

        }

        // GET: Products/Reply
        public ActionResult Reply(int productId, string userId, string question, int pos)
        {
            CommentViewModel model = new CommentViewModel { asker = userId, question = question, productId = productId, cont = pos };
            return View(model);
        }

        //POST: Products/Reply
        [HttpPost]
        public ActionResult ReplyPost(int productId, int cont, string reply)
        {
            Product product = db.Products.Find(productId);
            product.Questions.ElementAt(cont).reply = reply;
            var AdminData = db.AdminDatas.FirstOrDefault();
            AdminData.RepliedQuestions++;
            db.Entry(AdminData).State = EntityState.Modified;
            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Details", new { id = productId });
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByIdAsync(product.owner).Result;
            ViewBag.name = user.FullName;

            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult UserName2(Product model)
        {
            if (model == null)
            {
                return HttpNotFound();
            }

            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByIdAsync(model.owner).Result;
            ViewBag.name = user.FullName;
            return Content(user.FullName);
        }

        [HttpPost]
        public ActionResult Search(SearchViewModel model)
        {
            var products = from p in db.Products select p;
            if (!String.IsNullOrEmpty(model.Query))
            {
                products = products.Where(s => s.Name.Contains(model.Query));
            }

            return View(products.ToList());
        }

        public ActionResult UserName(Product model)
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByIdAsync(model.owner).Result;
            return Content(user.FullName);
        }

        // GET: Products/Create
        public ActionResult Create()
        {

            var model = new ProductViewModel { Categories = GetCategory() };
            return View(model);
        }

        
        public IEnumerable<SelectListItem> GetCategory()
        {
            var categories = db.Categories.ToList();
            List<SelectListItem> items = new List<SelectListItem>();

            

            foreach (var a in categories)
            {
                items.Add(new SelectListItem { Text = a.Name, Value = ""+a.Id });
            }

            return items;
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel model)
        {
            //var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                var product = new Product { Name = model.Name, Description = model.Description, CategoryId = model.SelectedCategoryId, Price = model.Price , SaleSpot = model.SaleSpot};
                product.Questions = new List<Question>();
                product.owner = User.Identity.GetUserId();
                HttpPostedFileBase ImageToUpload = Request.Files[0];

                var Filetype = ImageToUpload.ContentType;
                product.Picture = new Byte[ImageToUpload.ContentLength];
                ImageToUpload.InputStream.Read(product.Picture, 0, ImageToUpload.ContentLength);
                db.Products.Add(product);
                var AdminData = db.AdminDatas.FirstOrDefault();
                AdminData.AnnouncedItems++;
                db.Entry(AdminData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            model.Categories = GetCategory();

            return View(model);
        }

        public ActionResult Rating(String id)
        {  
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(id);
            if(user.NumberOfRatings > 5)
            {
                if(user.Rating < 5)  { return Content("not very trusted"); }
                if(user.Rating < 10) { return Content("caution when buying from this seller"); }
                if(user.Rating > 10) { return Content("trusted"); }
                if(user.Rating > 20) { return Content("very trusted"); }
                if(user.Rating > 30) { return Content("top seller"); }
            }
            return Content("not yet rated");
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);

            if(User.Identity.GetUserId() != product.owner)
            {
                return HttpNotFound();
            }
            if (product == null)
            {
                return HttpNotFound();
            }
            var model = new ProductViewModel { Id = product.Id, Name = product.Name, Description = product.Description, Price = product.Price, SelectedCategoryId = product.CategoryId, Picture = product.Picture, Categories = GetCategory(), SaleSpot = product.SaleSpot };
            return View(model);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductViewModel model)
        {
            //var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {

SecondHand/Views/Negotiations/Create.cshtml
@model SecondHand.Models.Negotiation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Negotiation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.seller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.seller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.seller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.buyer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.buyer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.buyer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SecondHand/Views/Negotiations/Delete.cshtml
@model SecondHand.Models.Negotiation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Negotiation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.seller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seller)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.buyer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.buyer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SecondHand/Views/Negotiations/Details.cshtml
@using Microsoft.AspNet.Identity
@using System.Data.Entity
@using System.Web
@using Microsoft.AspNet.Identity.EntityFramework
@using SecondHand.Models
@model SecondHand.Models.Negotiation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Negotiation</h4>
    <hr />
    <dl class="dl-horizontal">
        
        @{ 
            string userId = User.Identity.GetUserId();
        }
        @if (userId != Model.seller && userId != Model.buyer)
        {
            <dt>Not authorized.</dt>
            <br />
        }
        else if (User.Identity.GetUserId() == Model.buyer)
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(Model.seller);
            <p>Congratulations! To follow on your purchase please contact the seller at the following information:</p>
            <dt>Username:</dt> <dd>@user.FullName</dd>
            <dt>Email:</dt> <dd>@user.Email</dd>
            <dt>Phone:</dt> <dd>@user.PhoneNumber</dd>
            <br /><br />

            if (Model.control == 2)
            {
                <h3>Negotiation was ended successfully.</h3>
            }

            if (Model.control != 2)
            {
                if (Model.control == 1)
                {
                    using (Html.BeginForm("NegotiationSuccessful", "Negotiations", new { id = Model.id }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Negotiation successfull" class="btn btn-default" />
                            </div>
                        </div>
                        <br />
                        <br />
                    }
                }
                else
                {
                    <br />
                    <dd>Awaiting confirmation from seller on negotiation status.</dd>
                }
            }



            if (Model.control == 1 || Model.control == 0)
            {
                using (Html.BeginForm("TerminateNegotiation", "Negotiations", new { id = Model.id }))
                {
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Give up on negotiation" class="btn btn-default" />
                        </div>
                    </div>
                }
            }



        }
        else
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(Model.buyer);
            <p>Congratulations! To follow on your purchase please contact the buyer at the following information:</p>
            <dt>Username:</dt>
            <dd>@user.FullName</dd>
            <dt>Email:</dt>
            <dd>@user.Email</dd>
            <dt>Phone:</dt>
            <dd>@user.PhoneNumber</dd>
            <br />
            <br />

            if (Model.control == 2)
            {
                <h3>Negotiation was ended successfully.</h3>
            }

            if (Model.control != 2)
            {
                if (Model.control == 0)
                {
                    using (Html.BeginForm("NegotiationSuccessful", "Negotiations", new { id = Model.id }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Negotiation was successful" class="btn btn-default" />
                            </div>
                        </div>
                        <br />
                        <br />
                    }

                    using (Html.BeginForm("TerminateNegotiation", "Negotiations", new { id = Model.id }))
                    {
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Give up on negotiation" class="btn btn-default" />
                            </div>
                        </div>
                    }
                }
            }
        }






    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SecondHand/Views/Negotiations/Edit.cshtml
@model SecondHand.Models.Negotiation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Negotiation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.seller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.seller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.seller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.buyer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.buyer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.buyer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SecondHand/Views/Negotiations/Index.cshtml
@model IEnumerable<SecondHand.Models.Negotiation>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            Product
        </th>
        <th>
            Seller
        </th>
        <th>
            Buyer
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.Action("ProductName", "Products", new { id = item.productId })
        </td>
        <td>
            @Html.Action("UserName", "Home", new { id = item.seller })
        </td>
        <td>
            @Html.Action("UserName", "Home", new { id = item.buyer })
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.id })
        </td>
    </tr>
}

</table>

SecondHand/Views/Negotiations/Rating.cshtml
@model SecondHand.Models.ApplicationUser
@{
    ViewBag.Title = "Rating";
}

<h2>Rating</h2>

<h4>Thank you for buying at Second Hand!</h4>

<p>Please rate your experience with the seller @Html.Display(Model.FullName)</p>

@using (Html.BeginForm("RatingPost", "Negotiations", new { id = Model.Id }))
{   @Html.AntiForgeryToken()
    @Html.DropDownListFor(m => m.Rating, (SelectList)ViewBag.MyList, "-Please select-")

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Rate!" class="btn btn-default" />
        </div>
    </div>
}